name: Waka Readme

on:
  workflow_dispatch:
  schedule:
    # Runs at 00:00AM UTC
    - cron: "0 0 * * *"

jobs:
  update-readme:
    name: Update Readme with Metrics
    runs-on: ubuntu-latest
    steps:
      - uses: anmol098/waka-readme-stats@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          SHOW_LOC_CHART: "False"
          SHOW_PROFILE_VIEWS: "False"
          SHOW_PROJECTS: "False"
          SHOW_SHORT_INFO: "False"
          SHOW_UPDATED_DATE: "False"
          SHOW_LINES_OF_CODE: "False"
          SYMBOL_VERSION: "2"

{"data":{"human_readable_range":"last week","is_already_updating":false,"is_coding_activity_visible":true,"is_including_today":false,"is_other_usage_visible":true,"is_stuck":false,"is_up_to_date":false,"is_up_to_date_pending_future":false,"percent_calculated":71,"range":"last_7_days","status":"pending_update","timeout":15,"timezone":"Asia/Shanghai","username":"txtxj","writes_only":false},"message":"Calculating stats for this user. Check back later."}